Add ChirpStack helm chart
kuzzleio/helm-charts pull request #7
Opened 2023-02-20 13:11 UTC by Kuruyia

## What does this PR do ?
This adds the helm chart for deploying ChirpStack and its REST API bridge.

ChirpStack dependencies (Postgres, Redis & an MQTT broker) must be deployed separately, and the hosts of those services must be set accordingly when installing this chart.

2023-02-20 16:20 UTC, Aschen commented
I don't understand this sentence ` the hosts of those services must be set accordingly when installing this chart.`

Does it means that Chirpstack can be deployed on each client?

2023-02-20 16:39 UTC, Kuruyia commented
In our case, ChirpStack will not be deployed on each client but globally (although the helm chart has been written so it could be configured to be installed anywhere).

This sentence meant that, when installing the helm chart, you have to manually set the hostnames where ChirpStack can connect to the Postgres, the Redis and the MQTT broker.

2023-02-21 16:23 UTC, rolljee requested changes

2023-02-21 16:23 UTC, rolljee commented on charts/chirpstack/templates/chirpstack/cm.yaml
> +apiVersion: v1
You can give this file the proper fullname

2023-02-21 16:23 UTC, rolljee commented on charts/chirpstack/templates/chirpstack/cm.yaml
> +    [logging]
Could you add a link to the docs of this toml file in a comment

2023-02-21 16:23 UTC, rolljee commented on charts/chirpstack/templates/chirpstack/cm.yaml
> +    [[regions]]
Same here, add a link to this docs

2023-02-21 16:23 UTC, rolljee commented on charts/chirpstack/values.yaml
> +  regions:
This key name seems odd, region is rarely used for host configuration

2023-02-22 12:29 UTC, rolljee approved these changes

2023-02-23 14:51 UTC, merged